### ISSUE TITLE
Feature: Search all tabs and panes

### ISSUE THREAD

**Issue by rafi** [andersevenrud/compe-tmux#1]
It would be nice to have an option to search all panes in all tabs. :)

**Comment by andersevenrud** [comment]
Indeed! I'll look into that.

**Comment by andersevenrud** [comment]
Maybe you could test the branch in this pull-request: https://github.com/andersevenrud/compe-tmux/pull/2 ?

**Comment by andersevenrud** [comment]
I've been using this since I committed it and it seems to be working fine. So if you can confirm that I'll merge and release it :)

**Comment by andersevenrud** [comment]
I got some feedback on this and it seems to be working fine, so I went ahead and merged everything :)
