### ISSUE TITLE
Error on last update of cmp

### ISSUE THREAD

**Issue by LuisxSullivaN** [andersevenrud/compe-tmux#10]
I just updated my plugins via packer.nvim, nvim-cmp had quite a few updates and suddenly when I enter vim I get the following error message:
![image](https://user-images.githubusercontent.com/29529436/132017286-adf5b0d1-2b41-4170-942b-0bc6c1287606.png)

**Comment by joshniec** [comment]
It looks like the name of the function was changed from `config.get_source_option` to `config.get_source_config`. I changed this locally in my `compe-tmux_cmp/lua/compe_tmux/utils.lua` file and no longer get this error. I'll throw up a PR shortly to change this.

**Comment by andersevenrud** [comment]
Thanks for letting me know about this guys! Appreciate it. And thank you very much @joshniec, because I'm stuck at work currently :sweat_smile:

**Comment by andersevenrud** [comment]
Should be fixed now :blush:

**Comment by LuisxSullivaN** [comment]
Thanks!
