### ISSUE TITLE
Disable trigger chars

### ISSUE THREAD

**Issue by ranebrown** [andersevenrud/compe-tmux#12]
For the cmp branch is there a way to disable the trigger chars per filetype? When typing markdown I don't want a period at the end of a sentence to trigger completion. Thanks.

**Comment by andersevenrud** [comment]
If there isn't a way to do that via cmp settings, then I'd be happy to add this.

**Comment by andersevenrud** [comment]
According to the docs you can. And I tested this and it seems to do the trick :smile: 

```lua
{
    completion = {
        get_trigger_characters = function(trigger_characters)
            if vim.bo.filetype == 'markdown' then
                return {}
            end
            return trigger_characters
        end,
    },
}
```

**Comment by andersevenrud** [comment]
Maybe I was a bit too quick to close this ? This will remove the behavior of all extensions. But maybe that works fine with markdown ?

**Comment by andersevenrud** [comment]
Hm. Not feeling satisfied with the previous solution here, I went ahead and added support to customize this on a global and per filetype level.


You can now add this option to disable that trigger:

```
trigger_characters_ft = { markdown = { } }
```

More info in README on cmp branch.

**Comment by ranebrown** [comment]
Thanks!
