### ISSUE TITLE
Packer error

### ISSUE THREAD

**Issue by ranebrown** [andersevenrud/compe-tmux#13]
If using packer the following error pops up if there isn't a `packer_compiled.lua` file present.

```
Error detected while processing $HOME/.local/share/nvim/site/pack/packer/start/compe-tmux/after/plugin/compe_tmux.vim:
line    6:
E5108: Error executing lua vim/shared.lua:225: after the second argument: expected table, got nil
stack traceback:
        vim/shared.lua:225: in function 'create_compe_config'
        ...e/pack/packer/start/compe-tmux/lua/compe_tmux/source.lua:15: in function <...e/pack/packer/start/compe-tmux/lua/compe_tmux/source.lua:13>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

```

**Comment by andersevenrud** [comment]
Should be fixed now. Thanks for reporting :ok_hand:

**Comment by andersevenrud** [comment]
In hindsight I should have foreseen this scenario. The cmp API has had some sudden changes, and I have not had the time review all of it, which caused some unwanted side effects. So the commit message does not really reflect what actually went wrong... this is not really a packer thing but a cmp thing :man_shrugging:
