### ISSUE TITLE
How this should work?

### ISSUE THREAD

**Issue by alexzanderr** [andersevenrud/compe-tmux#14]
i have nvim-cmp installed and also cmp-tmux.

its configured like this:
```lua
local cmp = require("cmp")
cmp.setup({
	snippet = {
		expand = function(args)
			require"luasnip".lsp_expand(args.body)
		end
	},
	-- in this order they will appear in the box
	sources = {
		{ name = 'nvim_lsp' },
		{ name = 'luasnip' },
		{ name = 'buffer' },
		{ name = 'path' },
		{ name = 'nvim_lua' },
		{
			name = 'tmux',
			  opts = {
				all_panes = false,
				label = '[tmux]',
				trigger_characters = { '.' },
				trigger_characters_ft = {} -- { filetype = { '.' } }
			  }
		}
	},
	mapping = {
	  -- ['<C-d>'] = cmp.mapping.scroll_docs(-4),
	  -- ['<C-f>'] = cmp.mapping.scroll_docs(4),
	  ['<C-Space>'] = cmp.mapping.complete(),
	  ['<C-e>'] = cmp.mapping.close(),
	  -- ['<CR>'] = cmp.mapping.confirm({
	  --   select = true,
	  --   behavior = cmp.ConfirmBehavior.Replace,
	  -- }),
	  ['<CR>'] = cmp.mapping.abort(),
	  ['<tab>'] = cmp.mapping.confirm({
		select = true,
		behavior = cmp.ConfirmBehavior.Replace,
	  }),
	},
	formatting = {
	  format = function(entry, vim_item)
		-- fancy icons and a name of kind
		vim_item.kind = require("lspkind").presets.default[vim_item.kind] .. " " .. vim_item.kind

		-- set a name for each source
		vim_item.menu = ({
		  buffer = "[Buffer]",
		  nvim_lsp = "[LSP]",
		  luasnip = "[LuaSnip]",
		  nvim_lua = "[Lua]",
		  latex_symbols = "[Latex]",
		  -- https://github.com/andersevenrud/compe-tmux/issues/6
		  tmux = "[tmux]"
		})[entry.source.name]
		return vim_item
	  end,
	},

})
```
everything is fine.

but i dont understand where should i get completion from this plugin.

i was editing a `tmux.conf` file and there where no "tmux completion".

a better question is: what do you mean by `tmux completion`? tmux symbols completion? completion for commands?

**Comment by andersevenrud** [comment]
If you run neovim from within tmux with this plugin installed you will get completion items from other tmux buffers (adjacent ones by default).

You don't have to change your tmux configuration for this.

**Comment by alexzanderr** [comment]
you mean completion from other buffers opened in other neovims that are in other tmux panes?

**Comment by andersevenrud** [comment]
No, from other panes in your tmux session.

```
 ----------------------------------------
|                            |                            |
|                            |                            |
|             A             |             B             |
|                            |                            |
|                            |                            |
 ----------------------------------------
|                            |                            |
|                            |                            |
|            C              |             D             |
|                            |                            |
|                            |                            |
 ----------------------------------------
```

Imagine that you have a tmux open like this with 4 panes. In `A` you have neovim open, and in the other's you're doing some arbitrary work. All the text from the tmux buffers `B`, `C` and `D` will now be sourced as completions in neovim.

**Comment by alexzanderr** [comment]
> All the text from the tmux buffers B, C and D

so its just the text.

but what if in B, C and D i have neovim sessions? will i get completion from whats in the neovim buffers?

**Comment by andersevenrud** [comment]
> but what if in B, C and D i have neovim sessions? will i get completion from whats in the neovim buffers?

That should work.

**Comment by alexzanderr** [comment]
okey so i get:
- shell printed text on the terminal as completion options
- neovim words from opened buffers

cool, a lot of options.

**Comment by danielo515** [comment]
This should be added to the Readme, I was asking  myself the same

**Comment by andersevenrud** [comment]
@danielo515 I somehow missed your comment here. But I've added a brief a brief mention to how it works and a link to this issue in the README.
