### ISSUE TITLE
[BUG] Error when using Neovim within TMUX popup and nvim-cmp

### ISSUE THREAD

**Issue by lcrockett** [andersevenrud/compe-tmux#15]
When editing a buffer within Neovim that was started in a TMUX popup an error pops up, see screenshot below. Seems like it has trouble populating a table `tbl_map` when ran from within a TMUX popup.

I'm using Neovim 0.5.1-stable with `nvim-cmp` and am experiencing this issue both on MacOS Big Sur as well as Ubuntu 20.04. I have the `cmp` branch checked out. See below for my `nvim-cmp` configuration snippet.

A potential workaround is to specify `unset TMUX` in the shell that is running within the TMUX popup, prior to starting Neovim. However i'll be missing TMUX based completion in that case, which is not too bad considering i'm using TMUX popup's for short-lived and isolated actions.

```lua
require('cmp').setup {
  formatting = {
    format = require('lspkind').cmp_format({
      maxwidth = 80,
      menu = ({
        buffer = "[Buffer]",
        calc = "[calc]",
        nvim_lsp = "[LSP]",
        path = "[path]",
        tmux = "[TMUX]",
        spell = "[spell]",
        vsnip = "[vsnip]"
      }),
      with_text = true
    })
  },
  mapping = {
    ['<ESC>'] = function(fallback)
      require('cmp').close()
      fallback()
    end,
    ['<CR>'] = require('cmp').mapping.confirm({
      behavior = require('cmp').ConfirmBehavior.Insert,
      select = true
    }),
    ['<M-i>'] = require('cmp').mapping.scroll_docs(-4),
    ['<M-o>'] = require('cmp').mapping.scroll_docs(4),
    ['<M-n>'] = require('cmp').mapping.select_next_item({ behavior = require('cmp').SelectBehavior.Select }),
    ['<M-p>'] = require('cmp').mapping.select_prev_item({ behavior = require('cmp').SelectBehavior.Select })
  },
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end
  },
  sources = {
    { name = 'buffer' },
    { name = 'calc' },
    { name = 'nvim_lsp' },
    { name = 'path' },
    { name = 'tmux',
      opts = {
        all_panes = true,
        trigger_characters = { '.' }
      }
    },
    { name = 'spell' },
    { name = 'vsnip' }
  }
}
```

![image](https://user-images.githubusercontent.com/58056722/139508643-e1e22668-408c-4b9e-9061-c607610259a1.jpeg)

**Comment by andersevenrud** [comment]
Hi! Thanks for letting me know.

I've taken care of that error at least.

I was just about to head to bed, so I will look into the missing completion when using tmux popups. I don't actually think I've used that feature before :sweat_smile:

**Comment by lcrockett** [comment]
Thanks for the lightning fast fix, can confirm the error is gone. Cheers !

**Comment by andersevenrud** [comment]
Completions should be working now. At least if you use `:display-popup -E "nvim"`.

The issue was that a popup is technically not a pane, which means `TMUX_PANE` env variable was not set. Without this this source would just abort. Knowing this I've just removed the check entirely.

**Comment by lcrockett** [comment]
Cheers on the additional fix, can confirm opening Neovim in a TMUX popup works without errors and autocompletes using other TMUX panes as it's source.

**Comment by andersevenrud** [comment]
Glad to hear it! :)
