### ISSUE TITLE
[Deprecate 'opts' name] nvim-cmp will complain about deprecated 'opts' field

### ISSUE THREAD

**Issue by hiberabyss** [andersevenrud/compe-tmux#16]
May need to change the name from `opts` to `option`.

**Comment by andersevenrud** [comment]
Aha. I didn't catch this one: https://github.com/hrsh7th/nvim-cmp/commit/1944b463361984b06120a586f93bcf5ce1501b3b

This should really have been a breaking change. Oh, well. I will fix this ASAP when I get back home from work.

**Comment by andersevenrud** [comment]
Updated documentation for this. Thanks!

**Comment by hiberabyss** [comment]
Don't following code need changed to `source.option` ?

![image](https://user-images.githubusercontent.com/2898670/143468919-769318c7-3a18-4607-9fff-0c488a835272.png)

**Comment by andersevenrud** [comment]
You're right... :man_facepalming: Fixed
